Transitions/modals
wolox-training/ei-react-native pull request #15
Opened 2021-05-18 15:49 UTC by EstebanIndiveri

## Summary
Added new StackScreen Gallery and modal
Transition by navigation and Animated API,
tested component detailPost

## Screenshots

[Change!] Show the screenshots of the views you modified.

### Android
<a href="https://ibb.co/KDwmyj3"><img src="https://i.ibb.co/vhYDzxK/Screenshot-1621350142.png" alt="Screenshot-1621350142" border="0"></a>

#### Galaxy S (or similar)

<a href="https://ibb.co/18ZX7H0"><img src="https://i.ibb.co/WgnzGSH/Screenshot-1621350092.png" alt="Screenshot-1621350092" border="0"></a>
<a href="https://ibb.co/5Bqzdxv"><img src="https://i.ibb.co/r4nLgfM/Screenshot-1621350112.png" alt="Screenshot-1621350112" border="0"></a>
<a href="https://ibb.co/pPg57DP"><img src="https://i.ibb.co/RS1dFnS/Screenshot-1621350125.png" alt="Screenshot-1621350125" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'>web png</a><br />
#### Pixel 3XL (or similar)

### iOS

#### iPhone SE (or similar)

#### iPhone 6/7/8 (or similar)

#### iPhone 11/12 Base/Pro/Pro Max (or similar)

## Trello Card

[Change!] Link to the associated Trello card.

2021-05-18 16:53 UTC, mattgle requested changes

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/navigator/index.tsx
> +import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
this should be on line 18

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/index.tsx
> +import { SharedElement } from 'react-navigation-shared-element';
this 2 should be at line 4

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/index.tsx
> +  navigation: NavigationProp<PostsRoutes, 'post'>;
extract 'post'

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/index.tsx
> +      <SharedElement id={post.id}>
destructure post

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/styles.js
> +const { StyleSheet } = require('react-native');
why require? use import

2021-05-18 16:53 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +import { SharedElement } from 'react-navigation-shared-element';
native import with native imports pls

2021-05-18 17:18 UTC, andreszuluaga-wolox commented on wbooks/src/app/screens/Gallery/styles.js
> +    marginBottom: 15
use const to same values

2021-05-19 13:05 UTC, mattgle requested changes

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/navigator/index.tsx
> +import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
This import is an import from node_modules, so it should be next to those. In this case you should move this lineto line 4.

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/navigator/index.tsx
>  import { NavigationContainer } from '@react-navigation/native';
same comment

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/index.tsx
> +  navigation: NavigationProp<PostsRoutes, 'post'>;
...

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/DetailPost/styles.js
> +const TWENTYFIVE = 25;
? What happend to the comment i made about this?

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +    ));
destructure post

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +    </SafeAreaView>
is thi SafeAreaView needed?

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/Gallery/styles.js
> +const FIFTEEN = 15;
same comment.

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/app/screens/Gallery/styles.js
> +const { StyleSheet } = require('react-native');
why require? use imports.

2021-05-19 13:05 UTC, mattgle commented on wbooks/src/interfaces/posts.ts
> +  post: { post: Post };
this is weird. Why post: {post: } Cant you change the name? and why routes is undefined?

2021-05-19 16:18 UTC, mattgle requested changes

2021-05-19 16:18 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +        onPress={() => handlePress(id, source, avatar, user)}
```suggestion
        onPress={handlePress(id, source, avatar, user)}
```

2021-05-19 16:18 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +    };
```suggestion
    const handlePress = (id: string, source: string, avatar: string, user: string)  = () => {
      navigation.navigate(Routes.DetailPost, {
        post: { id, source, avatar, user }
      });
    };
```

2021-05-19 16:18 UTC, mattgle commented on wbooks/src/interfaces/posts.ts
> +  routes: RootStackParamList;
Cant you just use Routes?, i Mean its an enum

2021-05-20 11:30 UTC, mattgle approved these changes

2021-05-20 11:30 UTC, mattgle commented on wbooks/src/app/screens/Gallery/index.tsx
> +    const handlePress = (id: string, source: string, avatar: string, user: string) => () => {
why dont you use an object, and use the Post interface for props object?

2021-05-20 14:39 UTC, merged