Navigation book
wolox-training/ei-react-native pull request #6
Opened 2021-05-04 21:48 UTC by EstebanIndiveri

## Summary

Add React-navigation Stack

## Screenshots
<a href="https://ibb.co/c6Jy7FY"><img src="https://i.ibb.co/9bnpCTZ/screenshot-1620164445460.jpg" alt="screenshot-1620164445460" border="0"></a>
Android 9

### iOS

<a href="https://ibb.co/ZHY2PWp"><img src="https://i.ibb.co/1sdz58t/navigation2ios.png" alt="navigation2ios" border="0"></a>
#### iPhone 11/12 Base/Pro/Pro Max (or similar)

## Trello Card
[Trello card Link Navigation](https://trello.com/c/8LM05JxT/13-n-71-introducci%C3%B3n-a-react-navigation)

2021-05-04 22:20 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/CardBook/index.tsx
> +    <TouchableWithoutFeedback onPress={() => navigation.navigate('DetailBook', { image, title, author, id })}>
create a const and include this

2021-05-04 22:20 UTC, andreszuluaga-wolox commented on wbooks/src/app/screens/DetailBook/styles.js
> +    borderBottomLeftRadius: 20
use a const to same values

2021-05-05 13:35 UTC, mattgle requested changes

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/components/CardBook/index.tsx
> +    navigation.navigate('DetailBook', { image, title, author, id });
you can have a routes.ts file that contains all the Routes names from screens. U can import it then and use it here.

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/components/CardBook/index.tsx
> +    <TouchableWithoutFeedback onPress={handleClick}>
```suggestion
    <TouchableWithoutFeedback onPress={handlePress}>
```

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/components/CardBook/index.tsx
> +  const handleClick = () => {
```suggestion
  const handlePress = () => {
```

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/navigation/index.tsx
> +        name="Home"
You can use ROutes file here

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/navigation/index.tsx
> +        name="DetailBook"
You can use ROutes file here

2021-05-05 13:35 UTC, mattgle commented on wbooks/src/app/navigation/index.tsx
> +export default function Navigation(): ReactElement {
```suggestion
export default function Navigator(): ReactElement {
```

2021-05-05 13:35 UTC, andreszuluaga-wolox commented on wbooks/src/app/screens/DetailBook/styles.js
> +const platformMarginTop = Platform.OS === 'ios' ? 60 : 20;
to const use uppercase: `const BORDER_RADIUS_BOTTON`

2021-05-05 13:35 UTC, andreszuluaga-wolox commented on wbooks/src/app/screens/DetailBook/index.tsx
> +      )}
add view with backgroundColor when image is null

2021-05-05 16:06 UTC, mattgle requested changes

2021-05-05 16:06 UTC, mattgle commented on wbooks/src/app/routes/index.tsx
> +export const HOME = 'Home';
```suggestion
export default enum Routes {
DetailBook = 'DetailBook',
Home = 'Home'
}
```

2021-05-05 16:06 UTC, mattgle commented on wbooks/src/app/routes/index.tsx
> +export const HOME = 'Home';
The file should be called routes.ts and it MUST be at `src/constants`

2021-05-05 16:23 UTC, mattgle approved these changes

2021-05-05 18:44 UTC, merged