Component/header
wolox-training/ei-react-native pull request #7
Opened 2021-05-05 23:18 UTC by EstebanIndiveri

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.
in this Pull Request add a custom Header with icons and navigation, change screen detailBook 

## Screenshots

[Change!] Show the screenshots of the views you modified.

### Android

#### Galaxy S (or similar)
<a href="https://ibb.co/72c9mv7"><img src="https://i.ibb.co/0hNwbqP/Screenshot-1620255111.png" alt="Screenshot-1620255111" border="0"></a>

<a href="https://ibb.co/zZzDkzr"><img src="https://i.ibb.co/w4fjvfR/Screenshot-1620255122.png" alt="Screenshot-1620255122" border="0"></a>

#### Pixel 2/3 (or similar)
<a href="https://ibb.co/QkYMCCV"><img src="https://i.ibb.co/68DF11S/Screenshot-1620255075.png" alt="Screenshot-1620255075" border="0"></a>

<a href="https://ibb.co/GM4kpSC"><img src="https://i.ibb.co/s1dQRYs/Screenshot-1620255083.png" alt="Screenshot-1620255083" border="0"></a>

#### Horizontal test
<a href="https://ibb.co/BC80hQ8"><img src="https://i.ibb.co/wzD5nPD/Screenshot-2021-05-05-19-55-00-019-com-wbooks.jpg" alt="Screenshot-2021-05-05-19-55-00-019-com-wbooks" border="0"></a>

#### Pixel 3XL (or similar)

### iOS

#### iPhone SE (or similar)
<a href="https://ibb.co/tZHw3FF"><img src="https://i.ibb.co/s5gptzz/Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2021-05-05-at-19-50-37.png" alt="Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2021-05-05-at-19-50-37" border="0"></a>

<a href="https://ibb.co/VHs370G"><img src="https://i.ibb.co/n3FRHqy/Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2021-05-05-at-19-50-45.png" alt="Simulator-Screen-Shot-i-Phone-SE-2nd-generation-2021-05-05-at-19-50-45" border="0"></a>

#### iPhone 6/7/8 (or similar)
<a href="https://ibb.co/CJtYPwq"><img src="https://i.ibb.co/rbtzdQg/Simulator-Screen-Shot-i-Phone-8-2021-05-05-at-19-49-26.png" alt="Simulator-Screen-Shot-i-Phone-8-2021-05-05-at-19-49-26" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>speed jpg</a><br />

<a href="https://ibb.co/vXSJrVL"><img src="https://i.ibb.co/LN3CqY9/Simulator-Screen-Shot-i-Phone-8-2021-05-05-at-19-49-47.png" alt="Simulator-Screen-Shot-i-Phone-8-2021-05-05-at-19-49-47" border="0"></a>

#### iPhone 11/12 Base/Pro/Pro Max (or similar)
<a href="https://ibb.co/9rV4XF1"><img src="https://i.ibb.co/JsypLfG/Simulator-Screen-Shot-i-Phone-11-2021-05-05-at-19-50-19.png" alt="Simulator-Screen-Shot-i-Phone-11-2021-05-05-at-19-50-19" border="0"></a>

<a href="https://ibb.co/Zgx6sCM"><img src="https://i.ibb.co/xg6SvQ7/Simulator-Screen-Shot-i-Phone-11-2021-05-05-at-19-50-25.png" alt="Simulator-Screen-Shot-i-Phone-11-2021-05-05-at-19-50-25" border="0"></a>

## Trello Card

[Change!] Link to the associated Trello card.
[Header Trello Card](https://trello.com/c/RPvXQ03H/15-n-74-header)

2021-05-05 23:53 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/BackArrowIcon/index.tsx
> +      <View style={styles.imageContainer}>
this view not is necesary, use styles in `TouchableOpacity`

2021-05-05 23:53 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/BackArrowIcon/styles.js
> +    width: 20
the values is same, use conts, Example: `const ICON_SIZE = 20`

2021-05-05 23:53 UTC, andreszuluaga-wolox commented on wbooks/src/app/components/Header/index.tsx
> +export default function Header(): ReactElement {
@mattgle `ReactElement` is necesary?

2021-05-06 12:59 UTC, mattgle commented on wbooks/src/app/components/Header/index.tsx
> +export default function Header(): ReactElement {
No is not needed. But is now wrong.

2021-05-06 13:03 UTC, mattgle requested changes
Great work! Some comments!

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/BackArrowIcon/index.tsx
> +  };
```suggestion
  const handlePress = () =>     navigation.goBack();

```

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/BackArrowIcon/index.tsx
> +export default function BackArrowIcon(): ReactElement {
The ReactElement is not needed, it's not wrong, but its not needed.
```suggestion
export default function BackArrowIcon() {
```

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/NotificationIcon/index.tsx
> +import notifications from '@assets/General/ic_notifications.png';
```suggestion
import icNotification from '@assets/General/ic_notifications.png';
```

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/NotificationIcon/index.tsx
> +      <Image source={notifications} style={styles.image} resizeMethod="scale" resizeMode="contain" />
```suggestion
      <Image source={icNotification} style={styles.image} resizeMethod="scale" resizeMode="contain" />
```

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/NotificationIcon/index.tsx
> +    <View style={styles.imageContainer}>
Are you sure you need this View? Cant you just put the styles at the image?

2021-05-06 13:03 UTC, mattgle commented on wbooks/src/app/components/SerchIcon/index.tsx
> +export default function SeachIcon(): ReactElement {
This component is exactly the same as the NotificationIcon, you should make a generic component and send the image as a prop.

2021-05-06 14:42 UTC, mattgle approved these changes

2021-05-06 16:50 UTC, merged